---
galaxy_info:
  role_name: vector_role
  namespace: yastrebov
  author: yastrebov
  description: Install and configure Vector logging agent
  license: BSD
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "8"
    - name: Ubuntu
      versions:
        - "22.04"
        - "24.04"
  galaxy_tags:
    - vector
    - logging
dependencies: []
